### ISSUE TITLE
grepurl git link broken

### ISSUE THREAD

**Issue by lwahedi** [NLPbox/stanford-corenlp-docker#2]
https://github.com/foutaise/grepurl.git is broken. 
You can pip install grepurl, but it throws a syntax error because of the way an exception is written in the grepurl package.

**Comment by arne-cl** [comment]
Dear Laila,

thank you for bringing this to my attention! I have updated the Dockerfile accordingly.
The container is now also much smaller (using alpine instead of Ubuntu as its base).

Best,
Arne
